### ISSUE TITLE
What do you think about making it more flexible?

### ISSUE THREAD

**Issue by henriquebastos** [dobarkod/django-queryinspect#15]
This is an awesome project! Congrats! It'a amazing how complete it is.

For me it would be nice to be able to use the queryinspect programatically instead of coupling it to my project and making it depending on settings.

I teach a lot and work on many projects that need refactoring and performance improvements. So I think it would be great to use the inspector without the middleware.

I have some rudimentary solution for what I need with the `logdb` function fo [sqlformatter](https://github.com/henriquebastos/sqlformatter). [You can see the source at here](https://github.com/henriquebastos/sqlformatter/blob/master/sqlformatter.py).

Be decoupling the inspector from the predetermined workflow of a middleware one could:
- use as a view decorator
- use as a contextmanager
- turn it on on the beginning of a process and off somewhere else.
- easily integrate with other tools like django-debugtoolbar and django-devserver

If you feel this is aligned with your vision, I can do some work on that.

Again, congrats and thanks for sharing.

**Comment by senko** [comment]
Hey @henriquebastos thanks for the thoughtful post and for the kind words.

My main worry about the usefulness of qinspect is the fact that `DEBUG` must be on in order for sql queries to be inspected. So I’m not sure if using as a view decorator or context manager would be of much use. (If I understood your sqlformatter code correctly, you’re setting `DEBUG=True` in order to catch the statements — it may make sense in the case of sqlformatter but as it does have other effects, I wouldn’t be comfortable pulling the same trick in qinspect).

That said, I don’t see why decoupling qinspect start/stop/output from middleware request/response cycle would be a bad thing, and would encourage (and accept) contributions to that end :-)

**Comment by henriquebastos** [comment]
Hi! Thank you for the encouragement.

Clarifying: sqlformatter tries to be as little intrusive as possible to
Django. It relies the already available Django logging infrastructure to
log sql queries. It does not set `settings.DEBUG=True`, it simply adjusts
the Django's logger level.

My intent is to use `qinspect` *only* during development to explore the
code. The suggested api of contextmanager and view decorator would just
simplify code explorations.

 I'll hack on it as soon as I can and share some actual actual code.

**Comment by 4word** [comment]
Hi @henriquebastos, I had the exact same thought after I used query inspect for some of my API endpoints. I hope @senko and the rest of the contributors don't mind (I am sure they don't), but I used this project as a base for building [django-query-logger](https://github.com/4word/django-query-logger), which does almost exactly what your talking about. There is no decorator yet, but it performs the same functions as query inspect, but it can be turned on and off wherever and however you want throughout your code. Might be useful for you.

I would have made a pull request but I did most of the changes as part of my day job, and converting it back to working with the current query inspect would have been a pain. It was already rewritten as a class/mixin and I just threw it up there like that.

Would love to see the functionality in query inspector though, instead of maintaining my own project!

**Comment by senko** [comment]
Closing this issue as there hasn't been any action on it lately.

This doesn't mean I'm against refactoring django-queryinspect in the future as mentioned previously:

> I don’t see why decoupling qinspect start/stop/output from middleware request/response cycle would be a bad thing, and would encourage (and accept) contributions to that end :-)

I just personally don't have interest in doing so, but if anyone wants to do it (while maintaining backwards compatibility), I'd be happy to merge.
