### ISSUE TITLE
Is it thread-safe

### ISSUE THREAD

**Issue by tristanguo** [dobarkod/django-queryinspect#18]
As I know, middleware class is initialised once and shared by threads, in your class, your are using instance variables to store state, are you sure it is thread safe?

**Comment by senko** [comment]
Hey @tristanguo sorry for the slow response on this. To answer your question, I haven't used this in a multi-threaded environment, so I'm not sure (and you're probably right and it would break).

If you'd be willing to do some testing or contribute thread-safety-related changes, I'd love to get that into the package. Otherwise I'll try to look into it at some point myself.

**Comment by senko** [comment]
Closed as fixed in #28.
