### ISSUE TITLE
How to use for tests ?

### ISSUE THREAD

**Issue by vedavidhbudimuri** [dobarkod/django-queryinspect#20]
How would i use queryinspect for django tests ?

**Comment by mikeengland** [comment]
+1

**Comment by senko** [comment]
Hey @vedavidhbudimuri and @mikeengland, apologies for the slow response!

I don't know if you'd want to use qinspect in tests, I believe Django's `TransactionTestCase.assertNumQueries()` may be a better tool (you can assert that exactly some specified number of queries were executed while executing  a block of code).

That said, since qinspect can add headers carrying the sql execution data to the repsonse, you could examine/assert on those headers. It won't be very elegant, but it should work. If there's a good use case not covered by the `assertNumQueries` that qinspect can fill, I'm open to adding functionality to it to make it easier for use in tests.
