### ISSUE TITLE
Push a new release

### ISSUE THREAD

**Issue by orf** [dobarkod/django-queryinspect#24]
Hey,
Django-queryinspect is pretty useful, but currently there is no release that supports 1.10. Can you push an update to PyPi?

Thanks! And thanks for this library :+1:

**Comment by mdford** [comment]
and for version 1.11 please.  Are you planning on upgrading to support newer versions or is this module no longer supported or under active development?

Thanks!

**Comment by senko** [comment]
Hey @orf and @mdford - thanks for prodding and sorry for the delays on this.

The module is under active development and supported, and I've just tagged and uploaded the new 1.0.0 release:

* [PyPI](https://pypi.python.org/pypi/django-queryinspect/1.0.0)
* [source tarball](https://github.com/dobarkod/django-queryinspect/archive/1.0.0.tar.gz)

Fixed in 27ff754.

**Comment by mdford** [comment]
Hi @senko.  I can confirm that this does now work with django 1.11.1

Thanks so much for the upgrade!!
